Post  https://localhost:5001/livro HTTP/1.1
content-type: application/json

{
    "Titulo": "sample",
    "Capa": "Wed, 21 Oct 2015 18:27:50 GMT",
    "Sinopse": "Wed, 21 Oct 2015 18:27:50 GMT",
    "GeneroId" : "3",
    "Preco" : 3
}
###
PUT   https://localhost:5001/livro/4 HTTP/1.1
content-type: application/json

{
    "Titulo": "samplessssssssssssssssssss",
    "Capa": "Wed, 21 Oct 2015 18:27:50 GMT",
    "Sinopse": "Wed, 21 Oct 2015 18:27:50 GMT",
    "GeneroId" : 2,
    "Preco" : 3
}
####
GET    https://localhost:5001/livro HTTP/1.1
content-type: application/json

{
    "Titulo": "samplessss",
    "Capa": "Wed, 21 Oct 2015 18:27:50 GMT",
    "Sinopse": "Wed, 21 Oct 2015 18:27:50 GMT",
    "GeneroId" : 2
}
####
DELETE https://localhost:5001/livro/4 HTTP/1.1
content-type: application/json